### ISSUE TITLE
docker-composer up -d疑问

### ISSUE THREAD

**Issue by luoxulx** [gradydong/laravel-docker#1]
大佬你好，我可以用这套配置部署到线上吗？刚学docker，有点懵

**Comment by luoxulx** [comment]
看到没有发布releases版，有点怂

**Comment by gradydong** [comment]
> 大佬你好，我可以用这套配置部署到线上吗？刚学docker，有点懵

可以的，我就是用这个在线上部署的，已经用了很长时间了，只是才共享出来而已

**Comment by luoxulx** [comment]
![image](https://user-images.githubusercontent.com/35016570/48698576-63127f80-ec22-11e8-8469-1598f8847059.png)
今天在阿里的ECS上测试失败了，大佬可否看看是何缘故？

**Comment by gradydong** [comment]
> ![image](https://user-images.githubusercontent.com/35016570/48698576-63127f80-ec22-11e8-8469-1598f8847059.png)
> 今天在阿里的ECS上测试失败了，大佬可否看看是何缘故？

php-fpm 3.8 更新了 nodejs 没有安装npm ,现在把npm拆分出来了，安装一下就好了

**Comment by gradydong** [comment]
> ![image](https://user-images.githubusercontent.com/35016570/48698576-63127f80-ec22-11e8-8469-1598f8847059.png)
> 今天在阿里的ECS上测试失败了，大佬可否看看是何缘故？

我已经修改了，这个需要在nginx的dockerfile 单独安装一下npm

**Comment by luoxulx** [comment]
3Q, 已解决，但是又出现了一个新的问题，
![image](https://user-images.githubusercontent.com/35016570/48699766-31e77e80-ec25-11e8-8598-9a62db5a7a74.png)
还需要我创建什么 可执行文件吗？

**Comment by gradydong** [comment]
> 3Q, 已解决，但是又出现了一个新的问题，
> ![image](https://user-images.githubusercontent.com/35016570/48699766-31e77e80-ec25-11e8-8598-9a62db5a7a74.png)
> 还需要我创建什么 可执行文件吗？

我刚又执行了一下，没有这个问题，你具体是怎么执行的，或者你把所有的镜像删除了，重新执行一下，有具体问题的话，我可以给你看一下

**Comment by luoxulx** [comment]
我把镜像都删除了，重新docker-compose up -d，还是一样的error信息

**Comment by luoxulx** [comment]
- 之前是普通用户执行的，这次我换root身份删除完重新执行，一样的error信息。

- 重新clone到本地进入docker目录，还是一样的error信息

- google了一下说是update到最新的7.4，但我已经是最新的centos7.4了，期待comment

**Comment by gradydong** [comment]
> * 之前是普通用户执行的，这次我换root身份删除完重新执行，一样的error信息。
> * 重新clone到本地进入docker目录，还是一样的error信息
> * google了一下说是update到最新的7.4，但我已经是最新的centos7.4了，期待comment

找到原因了，是web 的docker-entrypoint.sh 没有可执行权限，已修改

**Comment by luoxulx** [comment]
非常3Q！已经successful了！你可以发布一个releases版本了

**Comment by luoxulx** [comment]
```
server {  
    listen  80;
    server_name xx.xxxx.xxx;

    set $root_path '/usr/share/nginx/html';
    set $php_path '/var/web/laravel-docker/laravel/public';

    client_max_body_size 100m;

    charset utf-8;
    
    index index.php index.html index.htm;    

    location ~ (\.html|\.css|\.js|\.jpg|\.jpeg|\.png|\.gif|\.ico|\.ttf|\.woff|\.woff2|\.xls|\.xlsx|\.docx|\.pdf|\.mpga|\.mp3|\.txt) {
		root $root_path;
	}

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    location ~ \.php {    
        root $php_path;
        fastcgi_pass app:9000;
        fastcgi_index /index.php;
    
        fastcgi_split_path_info          ^(.+\.php)(/.+)$;
        fastcgi_param PATH_INFO          $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param PATH_TRANSLATED    $document_root$fastcgi_path_info;
        include                          fastcgi_params;
        fastcgi_intercept_errors         on;
    }    

    location ~ /\.ht {    
        deny all;    
    }    
}
```
最后一个疑问，nginx配置文件是这样的吗？还是如何配置？如上配置会出错
```
Warning: require(/var/www/html/public/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/public/index.php on line 24

Fatal error: require(): Failed opening required '/var/www/html/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/index.php on line 24
```

**Comment by gradydong** [comment]
> ```
> server {  
>     listen  80;
>     server_name xx.xxxx.xxx;
> 
>     set $root_path '/usr/share/nginx/html';
>     set $php_path '/var/web/laravel-docker/laravel/public';
> 
>     client_max_body_size 100m;
> 
>     charset utf-8;
>     
>     index index.php index.html index.htm;    
> 
>     location ~ (\.html|\.css|\.js|\.jpg|\.jpeg|\.png|\.gif|\.ico|\.ttf|\.woff|\.woff2|\.xls|\.xlsx|\.docx|\.pdf|\.mpga|\.mp3|\.txt) {
> 		root $root_path;
> 	}
> 
>     location / {
>         try_files $uri $uri/ /index.php?$query_string;
>     }
>     
>     location ~ \.php {    
>         root $php_path;
>         fastcgi_pass app:9000;
>         fastcgi_index /index.php;
>     
>         fastcgi_split_path_info          ^(.+\.php)(/.+)$;
>         fastcgi_param PATH_INFO          $fastcgi_path_info;
>         fastcgi_param SCRIPT_FILENAME    $document_root$fastcgi_script_name;
>         fastcgi_param PATH_TRANSLATED    $document_root$fastcgi_path_info;
>         include                          fastcgi_params;
>         fastcgi_intercept_errors         on;
>     }    
> 
>     location ~ /\.ht {    
>         deny all;    
>     }    
> }
> ```
> 最后一个疑问，nginx配置文件是这样的吗？还是如何配置？如上配置会出错
> 
> ```
> Warning: require(/var/www/html/public/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/public/index.php on line 24
> 
> Fatal error: require(): Failed opening required '/var/www/html/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/index.php on line 24
> ```

出现这个问题是因为docker-compose.override.yml里面有配置挂载volumes  - ../laravel:/var/www/html，这个是把上一级的laravel 目录映射到docker容器APP 的/var/www/html目录，/var/www/html/就是nginx里面配置的PHP代码目录，开发环境的话，你会做各种修改，所以这种挂载的就是你本身的开发代码，生产环境的话，你把编译好的docker镜像打包，在你要部署的地方导入镜像，或者自己搭建registry，docker-composer pull 就可以了，docker-compose.override.yml把挂载给注释掉就行了

**Comment by luoxulx** [comment]
3Q，更新README.md就完美了
